openapi: 3.0.3
info:
  title: RideFlow User Service API
  description: REST API for managing RideFlow users (riders & drivers).
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local (Docker Compose via Gateway)

security:
  - bearerAuth: []

paths:
  /users:
    get:
      summary: List all users
      operationId: listUsers
      responses:
        "200":
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserRequest"
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateRequest"
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRequest"

  /users/{id}:
    get:
      summary: Get a user by ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRequest"
        "404":
          description: User not found

components:
  schemas:
    UserRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        keycloakId:
          type: string
          format: uuid
          example: "987fcdeb-51a2-43d7-9c8f-123456789abc"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        name:
          type: string
          example: "John Doe"
        role:
          type: string
          enum: [RIDER, DRIVER]
          example: "RIDER"
        createdAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
      required: [id, keycloakId, email, name, role]

    UserCreateRequest:
      type: object
      properties:
        keycloakId:
          type: string
          format: uuid
          example: "987fcdeb-51a2-43d7-9c8f-123456789abc"
        email:
          type: string
          format: email
          example: "jane.smith@example.com"
        name:
          type: string
          example: "Jane Smith"
        role:
          type: string
          enum: [RIDER, DRIVER]
          example: "DRIVER"
        vehicle:
          type: string
          example: "Toyota Camry 2022"
        licenseNumber:
          type: string
          example: "DL-1234567890"
      required: [keycloakId, email, name, role]
