openapi: 3.0.3
info:
  title: RideFlow Driver Service API
  version: 1.0.0
  description: |
    Unified API combining public and internal operations for the Driver Service.
servers:
  - url: http://localhost:8080
    description: Local (Docker Compose via Gateway)

paths:
  /drivers/{id}:
    get:
      summary: Get driver profile
      operationId: getDriver
      parameters:
        - $ref: '#/components/parameters/driverIdPath'
      responses:
        '200':
          description: Driver found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverPayload'
        '404': { $ref: '#/components/responses/NotFound' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/InternalError' }

  /drivers/{id}/status:
    patch:
      summary: Update driver status
      operationId: updateDriverStatus
      parameters:
        - $ref: '#/components/parameters/driverIdPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ status ]
              properties:
                status: { $ref: '#/components/schemas/DriverStatus' }
      responses:
        '200':
          description: Status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverPayload'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/InternalError' }

  /drivers/{id}/location:
    patch:
      summary: Update driver location
      operationId: updateDriverLocation
      parameters:
        - $ref: '#/components/parameters/driverIdPath'
      requestBody:
        $ref: '#/components/requestBodies/GeoLocationBody'
      responses:
        '200':
          description: Location updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverPayload'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/InternalError' }

  /drivers:
    post:
      summary: Create driver profile
      operationId: createDriver
      # security:
      #   - bearerAuth: []
      requestBody:
        $ref: '#/components/requestBodies/CreateDriverRequest'
      responses:
        '201':
          description: Driver created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverPayload'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '500': { $ref: '#/components/responses/InternalError' }

  /drivers/availability:
    get:
      summary: Check available drivers near a location
      operationId: checkAvailability
      # security:
      #   - internalAuth: []
      parameters:
        - $ref: '#/components/parameters/latQuery'
        - $ref: '#/components/parameters/lngQuery'
        - $ref: '#/components/parameters/radiusQuery'
      responses:
        '200':
          description: Availability info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailabilityResponse'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }
        '500': { $ref: '#/components/responses/InternalError' }

  /drivers/{id}/release:
    post:
      summary: Release driver after failed payment
      operationId: releaseDriver
      parameters:
        - $ref: '#/components/parameters/driverIdPath'
      # security:
      #   - internalAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DriverReleaseRequest'
      responses:
        '204':
          description: Driver released
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }
        '500': { $ref: '#/components/responses/InternalError' }

components:
  # securitySchemes:
  #   bearerAuth:
  #     type: http
  #     scheme: bearer
  #     bearerFormat: JWT
  #   internalAuth:
  #     type: apiKey
  #     in: header
  #     name: X-Keycloak-Secret

  schemas:
    DriverStatus:
      type: string
      enum: [ AVAILABLE, ON_TRIP, UNAVAILABLE ]

    GeoLocation:
      type: object
      required: [ lat, lng ]
      properties:
        lat: { type: number, format: double, minimum: -90, maximum: 90 }
        lng: { type: number, format: double, minimum: -180, maximum: 180 }

    DriverCreateRequest:
      type: object
      required: [ userId, vehicle, licenseNumber ]
      properties:
        userId: { type: string, format: uuid }
        vehicle: { type: string, example: "Toyota Prius 2023 - Silver" }
        licenseNumber: { type: string, example: "DL-2024-123456" }

    DriverPayload:
      type: object
      properties:
        id: { type: string, format: uuid }
        userId: { type: string, format: uuid }
        vehicle: { type: string, example: "Toyota Prius 2023 - Silver" }
        licenseNumber: { type: string, example: "DL-2024-123456" }
        status: { $ref: '#/components/schemas/DriverStatus' }
        location: { $ref: '#/components/schemas/GeoLocation' }
        updatedAt: { type: string, format: date-time }

    AvailabilityResponse:
      type: object
      properties:
        available: { type: boolean }
        count: { type: integer, minimum: 0 }

    DriverReleaseRequest:
      type: object
      required: [ driverId, rideId ]
      properties:
        driverId: { type: string, format: uuid }
        rideId: { type: string, format: uuid }

    Error:
      type: object
      required: [ code, message ]
      properties:
        code: { type: string }
        message: { type: string }
        details: { type: object, additionalProperties: true }

  parameters:
    driverIdPath:
      name: id
      in: path
      required: true
      schema: { type: string, format: uuid }

    latQuery:
      name: lat
      in: query
      required: true
      schema: { type: number, format: double, minimum: -90, maximum: 90 }

    lngQuery:
      name: lng
      in: query
      required: true
      schema: { type: number, format: double, minimum: -180, maximum: 180 }

    radiusQuery:
      name: radius
      in: query
      required: false
      schema: { type: number, format: double, default: 5, minimum: 0 }

  requestBodies:
    GeoLocationBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeoLocation'

    CreateDriverRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DriverCreateRequest'

    UpdateDriverStatusRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            required: [ status ]
            properties:
              status: { $ref: '#/components/schemas/DriverStatus' }

  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }
    Forbidden:
      description: Not permitted
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }
    InternalError:
      description: Server error
      content:
        application/json:
          schema: { $ref: '#/components/schemas/Error' }